apiVersion: experimental.kontinue.io/v1
kind: GitSource
metadata:
  name: test
spec:
  repository: "cirocosta/test"

---

apiVersion: experimental.kontinue.io/v1
kind: Workflow
metadata:
  name: test
spec:
  sources:
    - name: repo
  steps:
    - name: configmap
      sources: [repo]
      templates:
        - template: |-
            kind: ConfigMap
            apiVersion: v1
            metadata:
              generateName: "test-"
            data:
              foo: '{{ .Sources.repo.revision }}'
